site_name: my_python_package
site_description: A minimal but production-ready Python package scaffold
site_author: Diogo Ribeiro
site_url: https://my-python-package.readthedocs.io/

repo_name: DiogoRibeiro7/my_python_package
repo_url: https://github.com/DiogoRibeiro7/my_python_package
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: false
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DiogoRibeiro7
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/my-python-package/

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api.md
  - Development:
      - Contributing: contributing.md
      - Development Guide: development.md
      - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
