# Dependabot configuration file
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements files in the root directory
    directory: "/"
    # Check for updates once a week (Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Group dependencies to consolidate PRs
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "isort"
          - "ruff"
          - "mypy"
          - "pytest*"
          - "bandit"
          - "pre-commit"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "black"
          - "isort"
          - "ruff"
          - "mypy"
          - "pytest*"
          - "bandit"
          - "pre-commit"
    # Maximum number of open PRs
    open-pull-requests-limit: 10
    # Prefix PR titles
    commit-message:
      prefix: "deps"
      include: "scope"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "automerge"
    # Allow automatic merging
    reviewers:
      - "DiogoRibeiro7"
    assignees:
      - "DiogoRibeiro7"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github_actions"
      - "automerge"
    reviewers:
      - "DiogoRibeiro7"
    assignees:
      - "DiogoRibeiro7"
